apiVersion: v1
kind: Service
metadata:
  name: netflixapp
  labels:
    app: netflixapp
spec:
  type: NodePort
  selector:
    app: netflixapp
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    
      nodePort: 30080   
 
